//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ventas
    {
        public int Ventaid { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Producto { get; set; }
        public string NombreCliente { get; set; }
        public int Clienteid { get; set; }
        public int Productoid { get; set; }
        public int Cantidad { get; set; }
        public int Itebis { get; set; }
        public int Precio { get; set; }
        public int Total { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Producto Producto1 { get; set; }
    }
}
